# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 0.8.0
tutorial: false

countries: ["TW"]

enable:
  retrieve_databundle: true
  retrieve_databundle_sector: true
  retrieve_cutout: false
  build_cutout: false
  build_natura_raster: true
  progress_bar: true

run:
  name: "tw_test1_highs_2013_7d_4h_6b"
  sector_name: "tw_test1_highs_2013_7d_4h_6b"

scenario:
  clusters: [6]
  opts: [Co2L-4H]

snapshots:
  start: "2013-03-01"
  end: "2013-03-08"

clean_osm_data_options:
  threshold_voltage: 35000

base_network:
  min_voltage_substation_offshore: 35000
  min_voltage_rebase_voltage: 35000

electricity:
  co2limit: .inf
  co2base: 1.2e+8 # unit: kgCO2-eq, year 2025
  automatic_emission: false
  # Test 1 represents today's fixed system, so no candidate technologies are investable.
  extendable_carriers:
    Generator: []
    StorageUnit: []
    Store: []
    Link: []

atlite:
  default: cutout-2013-era5-tw

renewable:
  hydro:
    # --- change this to 6 based on ChatGPT's comment:
    # Taiwan has steep terrain, short rivers and strong spatial variation in rainfall.
    # Level 4 may aggregate hydrologically distinct catchments too heavily.
    hydrobasins_level: 6
    hydro_max_hours: "energy_capacity_totals_by_country"

solving:
  solver:
    name: highs
    options: highs-default
